apps/kaja/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import MonedaListView, MonedaCreateView, MonedaUpdateView, MonedaDeleteView


urlpatterns = [

    # URLS SOCIO
    url(r'^moneda/listar/$',
        login_required(MonedaListView.as_view()), name="moneda_list"),
    url(r'^moneda/crear/$', login_required(MonedaCreateView.as_view()), name="moneda_add"),
    url(r'^moneda/editar/(?P<pk>[^/]+)$',
        login_required(MonedaUpdateView.as_view()), name='moneda_update'),
    url(r'^moneda/eliminar/(?P<pk>[^/]+)$',
        login_required(MonedaDeleteView.as_view()), name='moneda_delete'),

]

copaiseg/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# add
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('apps.account.urls', namespace='account')),
    url(r'^', include('apps.usuario.urls', namespace='usuario')),
    url(r'^', include('apps.acopio.urls', namespace='acopio')),
    url(r'^', include('apps.pagopersonal.urls', namespace='pagopersonal')),
    url(r'^', include('apps.kaja.urls', namespace='kaja')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/kaja/models.py
from django.db import models
from apps.acopio.models import Acopio
# Create your models here.


class Cargo(models.Model):

    monto_ingreso = models.DecimalField(max_digits=20, decimal_places=2)
    tipo_cargo = models.CharField(max_length=50, blank=True)

    class Meta:
        verbose_name = "Cargo"
        verbose_name_plural = "Cargos"

    def __str__(self):
        return self.tipo_cargo

    def depos(self):
        return 'Por concepto de %s entro la suma de "%s"' % (self.tipo_cargo, self.monto_ingreso)


class Balance(models.Model):

    #persona = models.OneToOneField(Persona, on_delete=models.CASCADE)
    balance = models.DecimalField(max_digits=20, decimal_places=2)
    fecha = models.DateTimeField(auto_now_add=True)
    monto = models.DecimalField(max_digits=20, decimal_places=2)
    cargo = models.ForeignKey(Cargo, on_delete=models.CASCADE)
    acopio = models.ForeignKey(Acopio, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Balance"
        verbose_name_plural = "Balance"

    def __str__(self):
        return self.balance


class CajaEgreso(models.Model):

    fecha = models.DateTimeField(auto_now_add=True)
    num_comprobante = models.CharField(max_length=50, blank=True)
    acopio = models.ForeignKey(Acopio, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "CajaEgreso"
        verbose_name_plural = "CajaEgresos"

    def __str__(self):
        return self.acopio.socio.persona.first_name


class DetalleCaja(models.Model):

    cantidad = models.DecimalField(max_digits=20, decimal_places=2)
    descripcion = models.CharField(max_length=50, blank=True)
    precio_uni = models.DecimalField(
        'Precio Unitario', max_digits=20, decimal_places=2)
    total_egreso = models.DecimalField(
        'Precio a Pagar', max_digits=20, decimal_places=2)

    class Meta:
        verbose_name = "DetalleCaja"
        verbose_name_plural = "Detalles Caja"

    def __unicode__(self):
        return self.cantidad

apps/kaja/forms.py
# encoding: utf-8
from django import forms
from .models import Balance


class BalanceForm(forms.ModelForm):

    class Meta:
        model = Balance
        fields = ['balance', 'monto',
                  'cargo', 'acopio']

apps/kaja/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import Balance
from .forms import BalanceForm


class MonedaListView(ListView):
    model = Balance
    template_name = 'caja/moneda_list.html'


class MonedaCreateView(CreateView):
    model = Balance
    form_class = BalanceForm
    template_name = 'caja/moneda_form.html'
    success_url = reverse_lazy('kaja:moneda_list')


class MonedaUpdateView(UpdateView):
    model = Balance
    form_class = BalanceForm
    template_name = 'caja/moneda_form.html'
    success_url = reverse_lazy('kaja:moneda_list')

    def dispatch(self, *args, **kwargs):
        self.autor_id = kwargs['pk']
        return super(MonedaUpdateView, self).dispatch(*args, **kwargs)


class MonedaDeleteView(DeleteView):
    model = Balance
    template_name = 'caja/persona_delete.html'
    success_url = reverse_lazy('kaja:moneda_list')

apps/kaja/templates/caja/moneda_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Registrar nuevo Socio{% endblock %}
{% block titleheader %}Registro de Socio{% endblock titleheader %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}

    
        <button type="submit" class="btn btn-success btn-sm"><i class="fa fa-floppy-o fa-lg" aria-hidden="true"></i>&nbsp;Guardar</button>
        <a href="{% url 'kaja:moneda_list' %}" class="btn btn-warning btn-sm"><i class="fa fa-ban fa-lg" aria-hidden="true"></i>&nbsp;Cancelar</a>
    </form>
{% endblock content %}

apps/kaja/templates/caja/moneda_list.html
{% extends "base.html" %}

{% block title %}Lista de Monedas{% endblock %}
{% block titleheader %}Lista de Monedas{% endblock titleheader %}

{% block content %}

<div style="margin-bottom: 1em;">
    <a class="btn btn-success" href="{% url 'kaja:moneda_add' %}">
        <i class="fa fa-plus-circle fa-lg"></i>&nbsp; Nuevo Moneda
    </a>
</div>

<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
            <tr class="success">
                <th class="text-center">N</th>
                <th class="text-center">Balance</th>
                <th class="text-center">Fecha</th>
                <th class="text-center">Monto</th>
                <th class="text-center">Cargo</th>
            </tr>
        </thead>
        <tbody>
            {% for d in object_list %}
            <tr>
                <td>{{ d.id }}</td>
                <td>{{ d.balance }}</td>
                <td>{{ d.fecha }}</td>
                <td>{{ d.monto }}</td>
                <td>{{ d.cargo }}</td>
                <td>{{ d.acopio }}</td>
                <td>
                    <a class="btn btn-info btn-sm" href="{% url 'kaja:moneda_update' d.id %}"><i class="fa fa-pencil fa-lg" aria-hidden="true"></i>&nbsp; Edit</a>
                    <a class="btn btn-danger btn-sm text-bold" href="{% url 'kaja:moneda_delete' d.id %}"><i class="fa fa-trash fa-lg" aria-hidden="true"></i>&nbsp; Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% if is_paginated %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}">&laquo; Previous</a></li>
        {% else %}
            <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
            {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}">Next &raquo;</a></li>
        {% else %}
            <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
    </ul>
{% endif %}
    
{% endblock %}

apps/kaja/templates/caja/persona_delete.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <h3>¿Desea eliminar la moneda de<b>"{{ object.monto }}"</b>?</h3> 
        <button class="btn btn-danger" type="submit"><i class="fa fa-check fa-lg" aria-hidden="true"></i>&nbsp;Sí, eliminar</button>
        <a class= "btn btn-warning" href="{% url 'kaja:moneda_list' %}"><i class="fa fa-ban fa-lg" aria-hidden="true"></i>&nbsp;Cancelar</a>
    </form>
{% endblock %}