apps/account/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import (PersonaListView, PersonaCreateView,
                    PersonaUpdateView, PersonaDeleteView,
                    UsuarioListView, UsuarioCreateView,
                    UsuarioUpdateView, UsuarioDeleteView)
from . import views



urlpatterns = [
    # url(r'$', IndexView.as_view(), name="index"),

    # URLS PERSONA
    url(r'^persona/listar/$', login_required(PersonaListView.as_view()), name="persona_list"),
    url(r'^persona/crear/$', login_required(PersonaCreateView.as_view()), name="persona_add"),
    url(r'^persona/editar/(?P<pk>[^/]+)$',
        login_required(PersonaUpdateView.as_view()), name='persona_update'),
    url(r'^persona/eliminar/(?P<pk>[^/]+)$',
        login_required(PersonaDeleteView.as_view()), name='persona_delete'),

    # # URLS USUARIO
    url(r'^usuario/listar/$', login_required(UsuarioListView.as_view()), name="usuario_list"),
    url(r'^usuario/crear/$', login_required(UsuarioCreateView.as_view()), name="usuario_add"),
    url(r'^usuario/editar/(?P<pk>[^/]+)$',
        login_required(UsuarioUpdateView.as_view()), name='usuario_update'),
    url(r'^usuario/eliminar/(?P<pk>[^/]+)$',
        login_required(UsuarioDeleteView.as_view()), name='usuario_delete'),

    url(r'^con_ajax_cadena/$', views.ListaProductos2),
]

apps/acopio/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from .views import (SocioListView, SocioCreateView,
                    SocioUpdateView, SocioDeleteView,
                    ParcelaListView, ParcelaCreateView,
                    ParcelaUpdateView, ParcelaDeleteView,
                    AcopioDetalleListView, AcopioDetalleCreateView)


urlpatterns = [

    # URLS SOCIO
    url(r'^socio/listar/$', login_required(SocioListView.as_view()), name="socio_list"),
    url(r'^socio/crear/$', login_required(SocioCreateView.as_view()), name="socio_add"),
    url(r'^socio/editar/(?P<pk>[^/]+)$',
        login_required(SocioUpdateView.as_view()), name='socio_update'),
    url(r'^socio/eliminar/(?P<pk>[^/]+)$',
        login_required(SocioDeleteView.as_view()), name='socio_delete'),

    # URLS PARCELA
    url(r'^parcela/listar/$', login_required(ParcelaListView.as_view()), name="parcela_list"),
    url(r'^parcela/crear/$', login_required(ParcelaCreateView.as_view()), name="parcela_add"),
    url(r'^parcela/editar/(?P<pk>[^/]+)$',
        login_required(ParcelaUpdateView.as_view()), name='parcela_update'),
    url(r'^parcela/eliminar/(?P<pk>[^/]+)$',
        login_required(ParcelaDeleteView.as_view()), name='parcela_delete'),

    # URLS ACOPIO
    url(r'^acopio/listar/$', login_required(AcopioDetalleListView.as_view()), name="acopio_list"),
    url(r'^acopio/crear/$', login_required(AcopioDetalleCreateView.as_view()), name="acopio_add"),
    # url(r'^acopio/editar/(?P<pk>[^/]+)$',
    #     login_required(AcopioDetalleUpdateView.as_view()), name='acopio_update'),
]

apps/usuario/urls.py
from django.conf.urls import url
from .views import RegistroUsuario, Logeo, Inicio
from django.contrib.auth.decorators import login_required
from . import views


urlpatterns = [
    url(r'^registrar/$', login_required(RegistroUsuario.as_view()), name="registrarUser"),
    url(r'^accounts/login/$', Logeo.as_view(), name="login"),
    url(r'^salir/$', login_required(views.LogOut), name="logout"),
    url(r'^menu/', login_required(Inicio.as_view()), name="index"),
]

copaiseg/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# add
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('apps.account.urls', namespace='account')),
    url(r'^', include('apps.usuario.urls', namespace='usuario')),
    url(r'^', include('apps.acopio.urls', namespace='acopio')),
    url(r'^', include('apps.pagopersonal.urls', namespace='pagopersonal')),
    url(r'^', include('apps.kaja.urls', namespace='kaja')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}">
    
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
    <!-- AdminLTE Skins-->
    <link rel="stylesheet" href="{% static 'dist/css/skins/skin-blue.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <style type="text/css">
      .main-footer {
        line-height: .001em;
        z-index: 1000;
      }
    </style>

  <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
  <script src="{% static 'ajax_buscar.js' %}"></script>

</head>

<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <!-- Main Header -->
<header class="main-header">

    <a href="#" class="logo">
      <span class="logo-mini"><b>ACO</b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Copaiseg</b></span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Messages: style can be found in dropdown.less-->
          <li class="dropdown messages-menu">
            <!-- Menu toggle button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-envelope-o"></i>
              <span class="label label-success">4</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have 4 messages</li>
              <li>
                <!-- inner menu: contains the messages -->
                <ul class="menu">
                  <li><!-- start message -->
                    <a href="#">
                      <div class="pull-left">
                        <!-- User Image -->
                        <img src="{% static 'dist/img/user2-160x160.jpg' %}" class="img-circle" alt="User Image">
                      </div>
                      <!-- Message title and timestamp -->
                      <h4>
                        Support Team
                        <small><i class="fa fa-clock-o"></i> 5 mins</small>
                      </h4>
                      <!-- The message -->
                      <p>Why not buy a new awesome theme?</p>
                    </a>
                  </li>
                  <!-- end message -->
                </ul>
                <!-- /.menu -->
              </li>
              <li class="footer"><a href="#">See All Messages</a></li>
            </ul>
          </li>
          <!-- /.messages-menu -->

          <!-- Notifications Menu -->
          <li class="dropdown notifications-menu">
            <!-- Menu toggle button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-bell-o"></i>
              <span class="label label-warning">10</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have 10 notifications</li>
              <li>
                <!-- Inner Menu: contains the notifications -->
                <ul class="menu">
                  <li><!-- start notification -->
                    <a href="#">
                      <i class="fa fa-users text-aqua"></i> 5 new members joined today
                    </a>
                  </li>
                  <!-- end notification -->
                </ul>
              </li>
              <li class="footer"><a href="#">View all</a></li>
            </ul>
          </li>
          <!-- Tasks Menu -->
          <li class="dropdown tasks-menu">
            <!-- Menu Toggle Button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-flag-o"></i>
              <span class="label label-danger">9</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have 9 tasks</li>
              <li>
                <!-- Inner menu: contains the tasks -->
                <ul class="menu">
                  <li><!-- Task item -->
                    <a href="#">
                      <!-- Task title and progress text -->
                      <h3>
                        Design some buttons
                        <small class="pull-right">20%</small>
                      </h3>
                      <!-- The progress bar -->
                      <div class="progress xs">
                        <!-- Change the css width attribute to simulate progress -->
                        <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                          <span class="sr-only">20% Complete</span>
                        </div>
                      </div>
                    </a>
                  </li>
                  <!-- end task item -->
                </ul>
              </li>
              <li class="footer">
                <a href="#">View all tasks</a>
              </li>
            </ul>
          </li>

        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Bienvenido: {{ user.username }}<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#"><i class="fa fa-user" aria-hidden="true"></i> Perfil</a></li>
              <li><a href="#"><i class="fa fa-envelope" aria-hidden="true"></i> Mensajes</a></li>
              <li><a href="#"><i class="fa fa-cog" aria-hidden="true"></i> Opciones</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="{% url 'usuario:logout' %}"><i class="fa fa-power-off" aria-hidden="true"></i> Log Out</a></li>
            </ul>
          </li>
        </ul>

        </ul>
      </div>
    </nav>
</header>

  <!-- Left side column. contains the logo and sidebar rigth-->
<aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

      <!-- search form (Optional) -->
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Buscar...">
              <span class="input-group-btn">
                <button type="submit" name="Buscar" id="Buscar-btn" class="btn btn-flat"><i class="fa fa-Buscar"></i>
                </button>
              </span>
        </div>
      </form>
      <!-- /.search form -->

      <!-- Sidebar Menu -->
      <ul class="sidebar-menu">
        <li class="header">MENU</li>
        <!-- Optionally, you can add icons to the links -->
        <li class="active"><a href="{% url 'usuario:index' %}"><i class="fa fa-home fa-lg"></i> <span>Home</span></a></li>

        <li class="treeview">
          <a href="#"><i class="fa fa-user-secret" aria-hidden="true"></i><span>Socios</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{% url 'acopio:socio_add' %}">Nuevo<i class="fa fa-user-plus" aria-hidden="true"></i></a></li>
            <li><a href="{% url 'acopio:socio_list' %}">Listar</a></li>
          </ul>
        </li>

        <li class="treeview">
          <a href="#"><i class="fa fa-crop fa-lg"></i> <span>Parcela</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{% url 'acopio:parcela_add' %}">Nuevo<i class="fa fa-user-plus" aria-hidden="true"></i></a></li>
            <li><a href="{% url 'acopio:parcela_list' %}">Listar</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#"><i class="fa fa-cart-plus fa-lg"></i><span>Acopio</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{% url 'acopio:acopio_add' %}">Realizar Acopio</a></li>
            <li><a href="{% url 'acopio:acopio_list' %}">Lista de Acopio</a></li>
            <li><a href="#"></a></li>
          </ul>
        </li>

        <li class="treeview">
          <a href="#"><i class="fa fa-cogs fa-lg"></i> <span>Configuración</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{% url 'account:usuario_list' %}">Usuario</a></li>
          </ul>
        </li>
      </ul>
      <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        {% block titleheader %}
            
        {% endblock titleheader %}
        <small>Optional description</small>
      </h1>

      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
        <li class="active">Here</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        {% block content %} {% endblock content %}

    </section>
    <!-- /.content -->
</div>
  <!-- /.content-wrapper -->

  <!-- Main Footer -->
<footer class="main-footer navbar-inverse navbar-fixed-bottom hidden-xs">
    <!-- To the right -->
  <div class="container">
    <div class="pull-right hidden-xs">
      <p>Versión: 1.0 Hecho con <a href="#" target="_blank" >HTML</a> |
        <a href="#" target="_blank" >CSS</a>
      </p> 
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; {% now 'Y' %} <a href="#">UPeU</a>.</strong> All rights reserved.
  </div>      
</footer>

<div class="control-sidebar-bg"></div>

</div>
<!-- ./wrapper -->


    <script src="{% static 'jquery/jquery-3.2.1.js' %}"></script>
    <script src="{% static 'bootstrap/bootstrap.min.js' %}"></script>
    <script src="{% static 'dist/js/app.min.js' %}"></script>
</body>

</html>

templates/index.html
{% extends "base.html" %}

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %}Login{% endblock title %}</title>
{% block styles %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
{% endblock styles %}
<style type="text/css">
    body {
        background: linear-gradient(
                220deg,
                seagreen,
                rgba(0,0,0,.8)
                );
        background-image: url("http://www.timelyintervention.co.uk/wp-content/uploads/2014/06/Consulting.png");
        background-repeat: no-repeat;
        background-size: cover;
        background-attachment: fixed;
    }
</style>
</head>
<body>

    <form class="login-form" method="POST">
        <link rel="stylesheet" href="../static/css/styles.css">
        <!--img src="../../static/img/logo.png" height="100" width="100"-->

        {% csrf_token %}
        {{ form.username }}
        {{ form.username.errors }}

        {{ form.password }}
        {{ form.password.errors }}
        
        <input class="login-form_submit" type="submit" value="Ingresar">
        <a class="login-form_link" href="{% url 'usuario:index' %}">Registrarse</a>
    </form>
 
</body>
</html>