apps/account/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import (PersonaListView, PersonaCreateView,
                    PersonaUpdateView, PersonaDeleteView,
                    UsuarioListView, UsuarioCreateView,
                    UsuarioUpdateView, UsuarioDeleteView)
from . import views



urlpatterns = [
    # url(r'$', IndexView.as_view(), name="index"),

    # URLS PERSONA
    url(r'^persona/listar/$', login_required(PersonaListView.as_view()), name="persona_list"),
    url(r'^persona/crear/$', login_required(PersonaCreateView.as_view()), name="persona_add"),
    url(r'^persona/editar/(?P<pk>[^/]+)$',
        login_required(PersonaUpdateView.as_view()), name='persona_update'),
    url(r'^persona/eliminar/(?P<pk>[^/]+)$',
        login_required(PersonaDeleteView.as_view()), name='persona_delete'),

    # # URLS USUARIO
    url(r'^usuario/listar/$', login_required(UsuarioListView.as_view()), name="usuario_list"),
    url(r'^usuario/crear/$', login_required(UsuarioCreateView.as_view()), name="usuario_add"),
    url(r'^usuario/editar/(?P<pk>[^/]+)$',
        login_required(UsuarioUpdateView.as_view()), name='usuario_update'),
    url(r'^usuario/eliminar/(?P<pk>[^/]+)$',
        login_required(UsuarioDeleteView.as_view()), name='usuario_delete'),

    url(r'^con_ajax_cadena/$', views.ListaProductos2),
]

apps/pagopersonal/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import (PagoPersonalListView, PagoPersonalCreateView,
                    PagoPersonalUpdateView, PagoPersonalDeleteView,
                    )
from . import views


urlpatterns = [
    # url(r'$', IndexView.as_view(), name="index"),

    # URLS PERSONA
    url(r'^pagopersonal/listar/$',
        login_required(PagoPersonalListView.as_view()), name="pagopersonal_list"),
    url(r'^pagopersonal/crear/$',
        login_required(PagoPersonalCreateView.as_view()), name="pagopersonal_add"),
    url(r'^pagopersonal/editar/(?P<pk>[^/]+)$',
        login_required(PagoPersonalUpdateView.as_view()), name='pagopersonal_update'),
    url(r'^pagopersonal/eliminar/(?P<pk>[^/]+)$',
        login_required(PagoPersonalDeleteView.as_view()), name='pagopersonal_delete'),
]

copaiseg/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# add
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('apps.account.urls', namespace='account')),
    url(r'^', include('apps.usuario.urls', namespace='usuario')),
    url(r'^', include('apps.acopio.urls', namespace='acopio')),
    url(r'^', include('apps.pagopersonal.urls', namespace='pagopersonal')),
    url(r'^', include('apps.kaja.urls', namespace='kaja')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/pagopersonal/models.py
from django.db import models
from apps.account.models import Persona


class RegistroAsistencia(models.Model):


    fecha_acceso = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "RegistroAsistencia"
        verbose_name_plural = "RegistroAsistencias"

    def __str__(self):
        return self.fecha_acceso


class PagoPersonal(models.Model):

    cargo = models.CharField(max_length=20)
    monto = models.DecimalField(
        max_digits=10, decimal_places=2, blank=True, null=True)

    class Meta:
        verbose_name = "PagoPersonal"
        verbose_name_plural = "PagoPersonales"

    def __str__(self):
        return self.cargo

    def pays(self):
        return 'Yo como %s gano "%s"' % (self.cargo, self.monto)


class PersonalRegistro(models.Model):

    persona = models.ForeignKey(Persona, on_delete=models.CASCADE)
    pagopersonal = models.ForeignKey(PagoPersonal, on_delete=models.CASCADE)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    RUC = models.CharField(max_length=20)

    class Meta:
        verbose_name = "PersonalRegistro"
        verbose_name_plural = "PersonalRegistros"

    def __str__(self):
        return self.persona.first_name


class Personal(models.Model):

    #persona = models.OneToOneField(Persona, on_delete=models.CASCADE)
    #RUC = models.CharField(max_length=15)
    registro_asistencia = models.ForeignKey(
        RegistroAsistencia, on_delete=models.CASCADE)
    personal_registro = models.ForeignKey(
        PersonalRegistro, on_delete=models.CASCADE)
    fecha_pago = models.DateTimeField(auto_now_add=True)
    mes_correspondiente = models.CharField(max_length=20)
    pago_total = models.DecimalField(
        max_digits=4, decimal_places=2, blank=True, null=True)
    #socio = models.ForeignKey(Socio, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Personal"
        verbose_name_plural = "Personales"

    def __str__(self):
        return self.personal_registro.persona.first_name


class DetalleReciboHonorario(models.Model):

    #persona = models.OneToOneField(Persona, on_delete=models.CASCADE)
    #RUC = models.CharField(max_length=15)
    personal = models.ForeignKey(
        Personal, on_delete=models.CASCADE)
    concepto = models.CharField(max_length=20)
    suma_de = models.DecimalField(
        max_digits=4, decimal_places=2, blank=True, null=True)
    total_neto_recibido = models.DecimalField(
        max_digits=4, decimal_places=2, blank=True, null=True)
    #socio = models.ForeignKey(Socio, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "DetalleReciboHonorario"
        verbose_name_plural = "DetalleReciboHonorarios"

    def __str__(self):
        return self.concepto


class ReciboHonorario(models.Model):

    #persona = models.OneToOneField(Persona, on_delete=models.CASCADE)
    #RUC = models.CharField(max_length=15)
    detalle_recibo_honorarios = models.ForeignKey(
        DetalleReciboHonorario, on_delete=models.CASCADE)
    fecha_emision = models.DateTimeField(auto_now_add=True)
    num_recibo_honorarios = models.CharField(max_length=20)
    #socio = models.ForeignKey(Socio, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "ReciboHonorario"
        verbose_name_plural = "ReciboHonorarios"

    def __str__(self):
        return self.ReciboHonorario
# return "%s %s %s" % (self.acopio.socio.persona.first_name,
        # self.acopio.socio.persona.last_name,
        # self.parcela.codigo)

apps/pagopersonal/forms.py
# encoding: utf-8
from django import forms

from .models import PagoPersonal


class PagoPersonalForm(forms.ModelForm):

    class Meta:
        model = PagoPersonal
        fields = ['cargo', 'monto']


# class UsuarioForm(forms.ModelForm):

#     class Meta:
#         model = User
#         fields = ['username', 'password', 'groups', 'user_permissions',
#                   'is_staff', 'is_active', 'is_superuser', 'last_login',
#                   'date_joined', 'persona']

apps/pagopersonal/views.py
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .forms import PagoPersonalForm
from .models import PagoPersonal


# class IndexView(ListView):
#     model = Person
#     template_name = "index.html"


# VIEW Persona
class PagoPersonalListView(ListView):
    model = PagoPersonal
    template_name = "pagopersonal/pago_personal_list.html"
    context_object_name = 'pagopersonales'  # Default: object_list
    paginate_by = 7
    queryset = PagoPersonal.objects.all()  # Default: Model.objects.all()

    def get_queryset(self):
        return PagoPersonal.objects.all()


class PagoPersonalCreateView(CreateView):
    model = PagoPersonal
    form_class = PagoPersonalForm
    template_name = 'pagopersonal/pago_personal_form.html'
    success_url = reverse_lazy('pagopersonal:pagopersonal_list')


class PagoPersonalUpdateView(UpdateView):
    model = PagoPersonal
    form_class = PagoPersonalForm
    template_name = 'pagopersonal/pago_personal_form.html'
    success_url = reverse_lazy('pagopersonal:pagopersonal_list')

    def dispatch(self, *args, **kwargs):
        self.autor_id = kwargs['pk']
        return super(PagoPersonalUpdateView, self).dispatch(*args, **kwargs)


class PagoPersonalDeleteView(DeleteView):
    model = PagoPersonal
    template_name = 'pagopersonal/pago_personal_delete.html'
    success_url = reverse_lazy('pagopersonal:pagopersonal_list')

apps/pagopersonal/templates/pagopersonal/pago_personal_delete.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <h3>¿Desea eliminar el pago por <b>"{{ object.cargo }}"</b>?</h3> 
        <button class="btn btn-danger" type="submit"><i class="fa fa-check fa-lg" aria-hidden="true"></i>&nbsp;Sí, eliminar</button>
        <a class= "btn btn-warning" href="{% url 'pagopersonal:pagopersonal_list' %}"><i class="fa fa-ban fa-lg" aria-hidden="true"></i>&nbsp;Cancelar</a>
    </form>
{% endblock %}

apps/pagopersonal/templates/pagopersonal/pago_personal_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Registrar nuevo Pago de Perosonal{% endblock %}
{% block titleheader %}Registro de Pago de Personal{% endblock titleheader %}

{% block content %}

    <form method="POST"  class="modal-body">
        {% csrf_token %}
        {{ form|crispy }}

        <button type="submit" class="btn btn-success btn-sm"><i class="fa fa-floppy-o fa-lg" aria-hidden="true"></i>&nbsp;Guardar</button>
        <a href="{% url 'pagopersonal:pagopersonal_list' %}" class="btn btn-warning btn-sm"><i class="fa fa-ban fa-lg" aria-hidden="true"></i>&nbsp;Cancelar</a>
    </form>
    
{% endblock %}

apps/pagopersonal/templates/pagopersonal/pago_personal_list.html
{% extends "base.html" %}

{% block title %}Lista de Pagos de Personal{% endblock %}
{% block titleheader %}Lista de Pagos de Personal{% endblock titleheader %}

{% block content %}

<div style="margin-bottom: 1em;">
    <a class="btn btn-success" href="{% url 'pagopersonal:pagopersonal_add' %}">
        <i class="fa fa-plus-circle fa-lg"></i>&nbsp; Nuevo Pago Personal
    </a>
</div>

<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
            <tr class="success">
                <th class="text-center">N°</th>
                <th class="text-center">Cargo</th>
                <th class="text-center">Monto</th>
                <th class="btn-actions col-blocked text-center">Acciónes</th>
            </tr>
        </thead>
        <tbody>
            {% for d in object_list %}
            <tr>
                <td>{{ d.id }}</td>
                <td>{{ d.cargo }}</td>
                <td>{{ d.monto }}</td>
                <td>
                    <a class="btn btn-info btn-sm" href="{% url 'pagopersonal:pagopersonal_update' d.id %}"><i class="fa fa-pencil fa-lg" aria-hidden="true"></i>&nbsp; Edit</a>
                    <a class="btn btn-danger btn-sm text-bold" href="{% url 'pagopersonal:pagopersonal_delete' d.id %}"><i class="fa fa-trash fa-lg" aria-hidden="true"></i>&nbsp; Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% if is_paginated %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}">&laquo; Previous</a></li>
        {% else %}
            <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
            {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}">Next &raquo;</a></li>
        {% else %}
            <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
    </ul>
{% endif %}
    
{% endblock %}

apps/pagopersonal/templates/pagopersonal/personal_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}Registrar nuevo Usuario{% endblock %}
{% block titleheader %}Registro de Personas{% endblock titleheader %}

{% block content %}

    <form method="POST"  class="modal-body">
        {% csrf_token %}
        {{ form|crispy }}

        <button type="submit" class="btn btn-success btn-sm"><i class="fa fa-floppy-o fa-lg" aria-hidden="true"></i>&nbsp;Guardar</button>
        <a href="{% url 'account:persona_list' %}" class="btn btn-warning btn-sm"><i class="fa fa-ban fa-lg" aria-hidden="true"></i>&nbsp;Cancelar</a>
    </form>

{% endblock content %}

apps/pagopersonal/templates/pagopersonal/recibo_honorario.html
{% extends "base.html" %}

{% block title %}Lista de Personas{% endblock %}
{% block titleheader %}Lista de Personas{% endblock titleheader %}

{% block content %}

{% csrf_token %}

<!--div class=”form-group”>
    <input type="text" id="busqueda" name="busqueda" placeholder="Buscar"style="width: 400px;">
    <p id="resultado_busqueda"></p>
</div-->

<div class="ui-widget">
  <label for="tags1">Array de Cadenas: </label>
  <input id="tags1">
 </div>

<div style="margin-bottom: 1em;">
    <a class="btn btn-success" href="{% url 'account:persona_add' %}">
        <i class="fa fa-plus-circle fa-lg"></i>&nbsp; Nueva Persona
    </a>
</div>

<div class="table-responsive">
    <table class="table table-bordered table-hovered ">
        <thead>
            <tr>
                <th class="text-center">N°</th>
                <th class="text-center">Nombres y Apellidos</th>
                <th class="text-center">N° DNI</th>
                <th class="text-center">E-mail</th>
                <th class="text-center">Fecha de Nacimiento</th>
                <th class="text-center">Foto</th>
                <th class="btn-actions col-blocked text-center">Acciónes</th>
            </tr>
        </thead>
        <tbody>
            {% for d in object_list %}
            <tr>
                <td>{{ d.id }}</td>
                <td>{{ d.last_name }} {{ d.first_name }}</td>
                <td>{{ d.identity_num }}</td>
                <td>{{ d.email }}</td>
                <td>{{ d.fech_naci }}</td>
                <td></td>
                <td>
                    <a class="btn btn-info btn-sm" href="{% url 'account:persona_update' d.id %}"><i class="fa fa-pencil fa-lg" aria-hidden="true"></i>&nbsp; Edit</a>
                    <a class="btn btn-danger btn-sm text-bold" href="{% url 'account:persona_delete' d.id %}"><i class="fa fa-trash fa-lg" aria-hidden="true"></i>&nbsp; Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% if is_paginated %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}">&laquo; Previous</a></li>
        {% else %}
            <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
            {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}">Next &raquo;</a></li>
        {% else %}
            <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
    </ul>
{% endif %}
    
{% endblock %}