apps/acopio/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from .views import (SocioListView, SocioCreateView,
                    SocioUpdateView, SocioDeleteView,
                    ParcelaListView, ParcelaCreateView,
                    ParcelaUpdateView, ParcelaDeleteView,
                    AcopioDetalleListView, AcopioDetalleCreateView)


urlpatterns = [

    # URLS SOCIO
    url(r'^socio/listar/$', login_required(SocioListView.as_view()), name="socio_list"),
    url(r'^socio/crear/$', login_required(SocioCreateView.as_view()), name="socio_add"),
    url(r'^socio/editar/(?P<pk>[^/]+)$',
        login_required(SocioUpdateView.as_view()), name='socio_update'),
    url(r'^socio/eliminar/(?P<pk>[^/]+)$',
        login_required(SocioDeleteView.as_view()), name='socio_delete'),

    # URLS PARCELA
    url(r'^parcela/listar/$', login_required(ParcelaListView.as_view()), name="parcela_list"),
    url(r'^parcela/crear/$', login_required(ParcelaCreateView.as_view()), name="parcela_add"),
    url(r'^parcela/editar/(?P<pk>[^/]+)$',
        login_required(ParcelaUpdateView.as_view()), name='parcela_update'),
    url(r'^parcela/eliminar/(?P<pk>[^/]+)$',
        login_required(ParcelaDeleteView.as_view()), name='parcela_delete'),

    # URLS ACOPIO
    url(r'^acopio/listar/$', login_required(AcopioDetalleListView.as_view()), name="acopio_list"),
    url(r'^acopio/crear/$', login_required(AcopioDetalleCreateView.as_view()), name="acopio_add"),
    # url(r'^acopio/editar/(?P<pk>[^/]+)$',
    #     login_required(AcopioDetalleUpdateView.as_view()), name='acopio_update'),
]

copaiseg/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# add
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('apps.account.urls', namespace='account')),
    url(r'^', include('apps.usuario.urls', namespace='usuario')),
    url(r'^', include('apps.acopio.urls', namespace='acopio')),
    url(r'^', include('apps.pagopersonal.urls', namespace='pagopersonal')),
    url(r'^', include('apps.kaja.urls', namespace='kaja')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/acopio/models.py
from django.db import models
from apps.account.models import Persona


class Socio(models.Model):

    persona = models.OneToOneField(Persona, on_delete=models.CASCADE)
    cod_socio = models.CharField(max_length=6)
    direccion = models.CharField(max_length=50, blank=True)
    ciudad = models.CharField(max_length=50, blank=True)
    estado = models.BooleanField(default=True)

    updated_at = models.DateTimeField("Updated at", auto_now=True)
    created_at = models.DateTimeField("Created at", auto_now_add=True)

    class Meta:
        verbose_name = "Socio"
        verbose_name_plural = "Socios"

    def __str__(self):
        return self.persona.first_name


class Parcela(models.Model):

    codigo = models.CharField(max_length=8)
    ubicacion = models.CharField(max_length=20)
    area_cultivo = models.DecimalField(
        max_digits=4, decimal_places=2, blank=True, null=True)
    area_desarrollo = models.DecimalField(
        max_digits=4, decimal_places=2, blank=True, null=True)
    prod_estimado_tn = models.DecimalField(
        max_digits=4, decimal_places=2, blank=True, null=True)
    prod_estimado_kg = models.DecimalField(
        max_digits=4, decimal_places=2, blank=True, null=True)
    total_parcelas = models.IntegerField(blank=True, null=True)
    socio = models.ForeignKey(Socio, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Parcela"
        verbose_name_plural = "Parcelas"

    def __str__(self):
        return self.codigo


class Acopio(models.Model):
    socio = models.ForeignKey(Socio, on_delete=models.CASCADE)
    fech_acopio = models.DateTimeField(auto_now_add=True)
    estado = models.BooleanField(default=False)
    n_ticket = models.IntegerField()

    class Meta:
        verbose_name = "Acopio"
        verbose_name_plural = "Acopios"

    def __str__(self):
        return self.socio.persona.first_name


class DetalleAcopio(models.Model):
    parcela = models.ForeignKey(Parcela, on_delete=models.CASCADE)
    acopio = models.ForeignKey(Acopio)
    kilos = models.DecimalField(max_digits=20, decimal_places=2)
    precio_uni = models.DecimalField(
        'Precio Unitario', max_digits=20, decimal_places=2)
    total_pagar = models.DecimalField(
        'Precio a Pagar', max_digits=20, decimal_places=2, blank=True, null=True)
    # total_importe = models.aggregate(Sum('importe'))

    class Meta:
        verbose_name = "Detalle  Acopio"
        verbose_name_plural = "Detalles Acopio"

    def __str__(self):
        return "%s %s %s" % (self.acopio.socio.persona.first_name,
                             self.acopio.socio.persona.last_name,
                             self.parcela.codigo)

    def _get_importe(self):
        return self.precio_uni * self.total_pagar
    importe = property(_get_importe)

apps/acopio/forms.py
# encoding: utf-8
from django import forms

from apps.account.models import Persona
from .models import Socio, Parcela, Acopio, DetalleAcopio


class PersonaForm(forms.ModelForm):

    class Meta:
        model = Persona
        fields = ['first_name', 'last_name', 'identity_type',
                  'identity_num', 'photo', 'email', 'birth_date']
        labels = {
            'first_name': 'Nombre: ',
            'last_name': 'Apellidos: ',
            'identity_type': 'Tipo de Identidad: ',
            'identity_num': 'Número: ',
            'photo': 'Fotografía: ',
            'email': 'E-mail: ',
            'birth_date': 'Fecha de Nacimiento: ',
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'identity_num': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
        }


class SocioForm(forms.ModelForm):

    class Meta:
        model = Socio
        fields = ['cod_socio', 'direccion', 'ciudad',
                  'estado']
        labels = {
            'cod_socio': 'Codigo de Socio: ',
            'direccion': 'Dirección: ',
            'ciudad': 'Distrito: ',
            'estado': 'Estado: ',
        }
        # widgets = {
        #     'first_name': forms.TextInput(attrs={'class': 'form-control'}),
        #     'last_name': forms.TextInput(attrs={'class': 'form-control'}),
        #     'identity_num': forms.TextInput(attrs={'class': 'form-control'}),
        #     'email': forms.TextInput(attrs={'class': 'form-control'}),
        # }


class ParcelaForm(forms.ModelForm):

    class Meta:
        model = Parcela
        fields = ['codigo', 'ubicacion', 'area_cultivo', 'area_desarrollo',
                  'prod_estimado_tn', 'prod_estimado_kg', 'total_parcelas',
                  'socio']


class AcopioForm(forms.ModelForm):

    class Meta:
        model = Acopio
        fields = ['socio', 'estado', 'n_ticket']
        labels = {
            'socio': 'Proveedor ',
            'estado': 'Pagado?: ',
            'n_ticket': 'N° Ticket: ',
        }


class DetalleAcopioForm(forms.ModelForm):

    class Meta:
        model = DetalleAcopio
        fields = ['parcela', 'acopio', 'kilos', 'precio_uni', 'total_pagar']
        labels = {
            'parcela': 'Parcela: ',
            'acopio': 'Acopio:',
            'kilos': 'Cantidad en Kg.: ',
            'precio_uni': 'Acopiado a: ',
            'total_pagar': 'Total a pagar: ',
        }

apps/acopio/views.py
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from .models import Socio, Parcela, Acopio, DetalleAcopio
from apps.account.models import Persona
from .forms import SocioForm, PersonaForm, ParcelaForm, AcopioForm, DetalleAcopioForm


class SocioListView(ListView):
    model = Socio
    template_name = 'socio/socio_list.html'
    context_object_name = 'socio'  # Default: object_list
    paginate_by = 7
    queryset = Socio.objects.all()  # Default: Model.objects.all()

    def get_queryset(self):
        return Socio.objects.all()


class SocioCreateView(CreateView):
    model = Socio
    template_name = 'socio/socio_form.html'
    form_class = SocioForm
    second_forms_class = PersonaForm
    success_url = reverse_lazy('acopio:socio_list')

    def get_context_data(self, **kwargs):
        context = super(SocioCreateView, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class(self.request.GET)
        if 'form2' not in context:
            context['form2'] = self.second_forms_class(self.request.GET)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST)
        form2 = self.second_forms_class(request.POST)
        if form.is_valid() and form2.is_valid():
            socio = form.save(commit=False)
            socio.persona = form2.save()
            socio.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form,
                                                                 form2=form2))


class SocioUpdateView(UpdateView):
    model = Socio
    second_model = Persona
    template_name = 'socio/socio_form.html'
    form_class = SocioForm
    second_form_class = PersonaForm
    success_url = reverse_lazy('acopio:socio_list')

    def get_context_data(self, **kwargs):
        context = super(SocioUpdateView, self).get_context_data(**kwargs)
        pk = self.kwargs.get('pk', 0)
        socio = self.model.objects.get(id=pk)
        persona = self.second_model.objects.get(id=socio.persona_id)
        if 'form' not in context:
            context['form'] = self.form_class()
        if 'form2' not in context:
            context['form2'] = self.second_form_class(instance=persona)
        context['id'] = pk
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        id_socio = kwargs['pk']
        socio = self.model.objects.get(id=id_socio)
        persona = self.second_model.objects.get(id=socio.persona_id)
        form = self.form_class(request.POST, instance=socio)
        form2 = self.second_form_class(request.POST, instance=persona)
        if form.is_valid() and form2.is_valid():
            form.save()
            form2.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return HttpResponseRedirect(self.get_success_url())


class SocioDeleteView(DeleteView):
    model = Socio
    template_name = 'socio/socio_delete.html'
    success_url = reverse_lazy('acopio:socio_list')


# PARCELA
class ParcelaListView(ListView):
    model = Parcela
    template_name = 'parcela/parcela_list.html'
    context_object_name = 'parcela'  # Default: object_list
    paginate_by = 7
    queryset = Parcela.objects.all()  # Default: Model.objects.all()

    def get_queryset(self):
        return Parcela.objects.all()


class ParcelaCreateView(CreateView):
    model = Parcela
    form_class = ParcelaForm
    template_name = 'parcela/parcela_form.html'
    success_url = reverse_lazy('acopio:parcela_list')


class ParcelaUpdateView(UpdateView):
    model = Parcela
    form_class = ParcelaForm
    template_name = 'parcela/parcela_form.html'
    success_url = reverse_lazy('acopio:parcela_list')

    def dispatch(self, *args, **kwargs):
        self.autor_id = kwargs['pk']
        return super(ParcelaUpdateView, self).dispatch(*args, **kwargs)


class ParcelaDeleteView(DeleteView):
    model = Parcela
    template_name = 'parcela/parcela_delete.html'
    success_url = reverse_lazy('acopio:parcela_list')


# ACOPIO
class AcopioDetalleListView(ListView):
    model = DetalleAcopio
    template_name = 'acopio/acopio_list.html'
    context_object_name = 'acopio'  # Default: object_list
    paginate_by = 7
    queryset = DetalleAcopio.objects.all()  # Default: Model.objects.all()

    def get_queryset(self):
        return DetalleAcopio.objects.all()


class AcopioDetalleCreateView(CreateView):
    model = DetalleAcopio
    template_name = 'acopio/acopio_form.html'
    form_class = AcopioForm
    second_forms_class = DetalleAcopioForm
    success_url = reverse_lazy('acopio:acopio_list')

    def get_context_data(self, **kwargs):
        context = super(AcopioDetalleCreateView, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class(self.request.GET)
        if 'form2' not in context:
            context['form2'] = self.second_forms_class(self.request.GET)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST)
        form2 = self.second_forms_class(request.POST)
        if form.is_valid() and form2.is_valid():
            detalleacopio = form.save(commit=False)
            detalleacopio.acopio = form2.save()
            detalleacopio.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form,
                                                                 form2=form2))

# class AcopioDetalleUpdateView(UpdateView):
#     model = Socio
#     second_model = DetalleAcopio
#     template_name = 'socio/socio_form.html'
#     form_class = SocioForm
#     second_form_class = PersonaForm
#     success_url = reverse_lazy('acopio:socio_list')

#     def get_context_data(self, **kwargs):
#         context = super(SocioUpdateView, self).get_context_data(**kwargs)
#         pk = self.kwargs.get('pk', 0)
#         socio = self.model.objects.get(id=pk)
#         persona = self.second_model.objects.get(id=socio.persona_id)
#         if 'form' not in context:
#             context['form'] = self.form_class()
#         if 'form2' not in context:
#             context['form2'] = self.second_form_class(instance=persona)
#         context['id'] = pk
#         return context

#     def post(self, request, *args, **kwargs):
#         self.object = self.get_object
#         id_socio = kwargs['pk']
#         socio = self.model.objects.get(id=id_socio)
#         persona = self.second_model.objects.get(id=socio.persona_id)
#         form = self.form_class(request.POST, instance=socio)
#         form2 = self.second_form_class(request.POST, instance=persona)
#         if form.is_valid() and form2.is_valid():
#             form.save()
#             form2.save()
#             return HttpResponseRedirect(self.get_success_url())
#         else:
#             return HttpResponseRedirect(self.get_success_url())

apps/acopio/templates/parcela/parcela_delete.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <h3>¿Desea eliminar la parcela de<b>"{{ object.socio.persona.first_name }} {{ object.socio.persona.last_name }}"</b>?</h3> 
        <button class="btn btn-danger" type="submit"><i class="fa fa-check fa-lg" aria-hidden="true"></i>&nbsp;Sí, eliminar</button>
        <a class= "btn btn-warning" href="{% url 'acopio:parcela_list' %}"><i class="fa fa-ban fa-lg" aria-hidden="true"></i>&nbsp;Cancelar</a>
    </form>
{% endblock %}

apps/acopio/templates/parcela/parcela_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}Registrar nueva Parcela{% endblock %}
{% block titleheader %}Registro de Parcela{% endblock titleheader %}

{% block content %}

    <form method="POST"  class="modal-body">
        {% csrf_token %}
        {{ form|crispy }}

        <button type="submit" class="btn btn-success btn-sm"><i class="fa fa-floppy-o fa-lg" aria-hidden="true"></i>&nbsp;Guardar</button>
        <a href="{% url 'acopio:parcela_list' %}" class="btn btn-warning btn-sm"><i class="fa fa-ban fa-lg" aria-hidden="true"></i>&nbsp;Cancelar</a>
    </form>

{% endblock content %}

apps/acopio/templates/parcela/parcela_list.html
{% extends "base.html" %}

{% block title %}Lista de Parcelas{% endblock %}
{% block titleheader %}Lista de Parcelas{% endblock titleheader %}

{% block content %}

{% csrf_token %}

<!--div class=”form-group”>
    <input type="text" id="busqueda" name="busqueda" placeholder="Buscar"style="width: 400px;">
    <p id="resultado_busqueda"></p>
</div-->

<div class="ui-widget">
  <label for="tags1">Array de Cadenas: </label>
  <input id="tags1">
 </div>

<div style="margin-bottom: 1em;">
    <a class="btn btn-success" href="{% url 'acopio:parcela_add' %}">
        <i class="fa fa-plus-circle fa-lg"></i>&nbsp; Nueva Parcela
    </a>
</div>

<div class="table-responsive">
    <table class="table table-bordered table-hovered ">
        <thead>
            <tr>
                <th class="text-center">N°</th>
                <th class="text-center">Nombres y Apellidos</th>
                <th class="text-center">N° DNI</th>
                <th class="text-center">E-mail</th>
                <th class="text-center">Fecha de Nacimiento</th>
                <th class="text-center">Foto</th>
                <th class="btn-actions col-blocked text-center">Acciónes</th>
            </tr>
        </thead>
        <tbody>
            {% for d in object_list %}
            <tr>
                <td>{{ d.id }}</td>
                <td>{{ d.codigo }}</td>
                <td>{{ d.area_cultivo }}</td>
                <td>{{ d.area_desarrollo }}</td>
                <td>{{ d.prod_estimado_tn }}</td>
                <td>{{ d.prod_estimado_kg }}</td>
                <td>{{ d.total_parcelas }}</td>
                <td>{{ d.socio }}</td>
                <td>
                    <a class="btn btn-info btn-sm" href="{% url 'acopio:parcela_update' d.id %}"><i class="fa fa-pencil fa-lg" aria-hidden="true"></i>&nbsp; Edit</a>
                    <a class="btn btn-danger btn-sm text-bold" href="{% url 'acopio:parcela_delete' d.id %}"><i class="fa fa-trash fa-lg" aria-hidden="true"></i>&nbsp; Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% if is_paginated %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}">&laquo; Previous</a></li>
        {% else %}
            <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
            {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}">Next &raquo;</a></li>
        {% else %}
            <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
    </ul>
{% endif %}
    
{% endblock %}